// This file was autogenerated by hardhat-viem, do not edit it.
// prettier-ignore
// tslint:disable
// eslint-disable

import "hardhat/types/artifacts";
import type { GetContractReturnType } from "@nomicfoundation/hardhat-viem/types";

import { SiweParser$Type } from "./SiweParser";

declare module "hardhat/types/artifacts" {
  interface ArtifactsMap {
    ["SiweParser"]: SiweParser$Type;
    ["@oasisprotocol/sapphire-contracts/contracts/SiweParser.sol:SiweParser"]: SiweParser$Type;
  }

  interface ContractTypesMap {
    ["SiweParser"]: GetContractReturnType<SiweParser$Type["abi"]>;
    ["@oasisprotocol/sapphire-contracts/contracts/SiweParser.sol:SiweParser"]: GetContractReturnType<SiweParser$Type["abi"]>;
  }
}
