// This file was autogenerated by hardhat-viem, do not edit it.
// prettier-ignore
// tslint:disable
// eslint-disable

import type { Address } from "viem";
import type { GetContractReturnType } from "@nomicfoundation/hardhat-viem/types";
import "@nomicfoundation/hardhat-viem/types";

export interface SiweParser$Type {
  "_format": "hh-sol-artifact-1",
  "contractName": "SiweParser",
  "sourceName": "@oasisprotocol/sapphire-contracts/contracts/SiweParser.sol",
  "abi": [
    {
      "inputs": [],
      "name": "SiweParser_InvalidAddressLength",
      "type": "error"
    },
    {
      "inputs": [],
      "name": "SiweParser_InvalidNonce",
      "type": "error"
    }
  ],
  "bytecode": "0x60566050600b82828239805160001a6073146043577f4e487b7100000000000000000000000000000000000000000000000000000000600052600060045260246000fd5b30600052607381538281f3fe73000000000000000000000000000000000000000030146080604052600080fdfea2646970667358221220bf8be3ece4e55f3265859d4cbf1bf928cf1fa17e5dd7d4bd7a80a864a0cbe32964736f6c634300081e0033",
  "deployedBytecode": "0x73000000000000000000000000000000000000000030146080604052600080fdfea2646970667358221220bf8be3ece4e55f3265859d4cbf1bf928cf1fa17e5dd7d4bd7a80a864a0cbe32964736f6c634300081e0033",
  "linkReferences": {},
  "deployedLinkReferences": {}
}

declare module "@nomicfoundation/hardhat-viem/types" {
  export function deployContract(
    contractName: "SiweParser",
    constructorArgs?: [],
    config?: DeployContractConfig
  ): Promise<GetContractReturnType<SiweParser$Type["abi"]>>;
  export function deployContract(
    contractName: "@oasisprotocol/sapphire-contracts/contracts/SiweParser.sol:SiweParser",
    constructorArgs?: [],
    config?: DeployContractConfig
  ): Promise<GetContractReturnType<SiweParser$Type["abi"]>>;

  export function sendDeploymentTransaction(
    contractName: "SiweParser",
    constructorArgs?: [],
    config?: SendDeploymentTransactionConfig
  ): Promise<{
    contract: GetContractReturnType<SiweParser$Type["abi"]>;
    deploymentTransaction: GetTransactionReturnType;
  }>;
  export function sendDeploymentTransaction(
    contractName: "@oasisprotocol/sapphire-contracts/contracts/SiweParser.sol:SiweParser",
    constructorArgs?: [],
    config?: SendDeploymentTransactionConfig
  ): Promise<{
    contract: GetContractReturnType<SiweParser$Type["abi"]>;
    deploymentTransaction: GetTransactionReturnType;
  }>;

  export function getContractAt(
    contractName: "SiweParser",
    address: Address,
    config?: GetContractAtConfig
  ): Promise<GetContractReturnType<SiweParser$Type["abi"]>>;
  export function getContractAt(
    contractName: "@oasisprotocol/sapphire-contracts/contracts/SiweParser.sol:SiweParser",
    address: Address,
    config?: GetContractAtConfig
  ): Promise<GetContractReturnType<SiweParser$Type["abi"]>>;
}
