// This file was autogenerated by hardhat-viem, do not edit it.
// prettier-ignore
// tslint:disable
// eslint-disable

import "hardhat/types/artifacts";
import type { GetContractReturnType } from "@nomicfoundation/hardhat-viem/types";

import { FireToken$Type } from "./FireToken";

declare module "hardhat/types/artifacts" {
  interface ArtifactsMap {
    ["FireToken"]: FireToken$Type;
    ["contracts/FireToken.sol:FireToken"]: FireToken$Type;
  }

  interface ContractTypesMap {
    ["FireToken"]: GetContractReturnType<FireToken$Type["abi"]>;
    ["contracts/FireToken.sol:FireToken"]: GetContractReturnType<FireToken$Type["abi"]>;
  }
}
