// This file was autogenerated by hardhat-viem, do not edit it.
// prettier-ignore
// tslint:disable
// eslint-disable

import "hardhat/types/artifacts";
import type { GetContractReturnType } from "@nomicfoundation/hardhat-viem/types";

import { DateTime$Type } from "./DateTime";

declare module "hardhat/types/artifacts" {
  interface ArtifactsMap {
    ["DateTime"]: DateTime$Type;
    ["@oasisprotocol/sapphire-contracts/contracts/DateTime.sol:DateTime"]: DateTime$Type;
  }

  interface ContractTypesMap {
    ["DateTime"]: GetContractReturnType<DateTime$Type["abi"]>;
    ["@oasisprotocol/sapphire-contracts/contracts/DateTime.sol:DateTime"]: GetContractReturnType<DateTime$Type["abi"]>;
  }
}
