// This file was autogenerated by hardhat-viem, do not edit it.
// prettier-ignore
// tslint:disable
// eslint-disable

import type { Address } from "viem";
import type { GetContractReturnType } from "@nomicfoundation/hardhat-viem/types";
import "@nomicfoundation/hardhat-viem/types";

export interface DateTime$Type {
  "_format": "hh-sol-artifact-1",
  "contractName": "DateTime",
  "sourceName": "@oasisprotocol/sapphire-contracts/contracts/DateTime.sol",
  "abi": [],
  "bytecode": "0x60566050600b82828239805160001a6073146043577f4e487b7100000000000000000000000000000000000000000000000000000000600052600060045260246000fd5b30600052607381538281f3fe73000000000000000000000000000000000000000030146080604052600080fdfea2646970667358221220a036d7e8f9c5babce18593c7191638b13e4903f21b002d05969b7f485c4914a864736f6c634300081e0033",
  "deployedBytecode": "0x73000000000000000000000000000000000000000030146080604052600080fdfea2646970667358221220a036d7e8f9c5babce18593c7191638b13e4903f21b002d05969b7f485c4914a864736f6c634300081e0033",
  "linkReferences": {},
  "deployedLinkReferences": {}
}

declare module "@nomicfoundation/hardhat-viem/types" {
  export function deployContract(
    contractName: "DateTime",
    constructorArgs?: [],
    config?: DeployContractConfig
  ): Promise<GetContractReturnType<DateTime$Type["abi"]>>;
  export function deployContract(
    contractName: "@oasisprotocol/sapphire-contracts/contracts/DateTime.sol:DateTime",
    constructorArgs?: [],
    config?: DeployContractConfig
  ): Promise<GetContractReturnType<DateTime$Type["abi"]>>;

  export function sendDeploymentTransaction(
    contractName: "DateTime",
    constructorArgs?: [],
    config?: SendDeploymentTransactionConfig
  ): Promise<{
    contract: GetContractReturnType<DateTime$Type["abi"]>;
    deploymentTransaction: GetTransactionReturnType;
  }>;
  export function sendDeploymentTransaction(
    contractName: "@oasisprotocol/sapphire-contracts/contracts/DateTime.sol:DateTime",
    constructorArgs?: [],
    config?: SendDeploymentTransactionConfig
  ): Promise<{
    contract: GetContractReturnType<DateTime$Type["abi"]>;
    deploymentTransaction: GetTransactionReturnType;
  }>;

  export function getContractAt(
    contractName: "DateTime",
    address: Address,
    config?: GetContractAtConfig
  ): Promise<GetContractReturnType<DateTime$Type["abi"]>>;
  export function getContractAt(
    contractName: "@oasisprotocol/sapphire-contracts/contracts/DateTime.sol:DateTime",
    address: Address,
    config?: GetContractAtConfig
  ): Promise<GetContractReturnType<DateTime$Type["abi"]>>;
}
