// This file was autogenerated by hardhat-viem, do not edit it.
// prettier-ignore
// tslint:disable
// eslint-disable

import "hardhat/types/artifacts";
import type { GetContractReturnType } from "@nomicfoundation/hardhat-viem/types";

import { EthereumUtils$Type } from "./EthereumUtils";

declare module "hardhat/types/artifacts" {
  interface ArtifactsMap {
    ["EthereumUtils"]: EthereumUtils$Type;
    ["@oasisprotocol/sapphire-contracts/contracts/EthereumUtils.sol:EthereumUtils"]: EthereumUtils$Type;
  }

  interface ContractTypesMap {
    ["EthereumUtils"]: GetContractReturnType<EthereumUtils$Type["abi"]>;
    ["@oasisprotocol/sapphire-contracts/contracts/EthereumUtils.sol:EthereumUtils"]: GetContractReturnType<EthereumUtils$Type["abi"]>;
  }
}
