// This file was autogenerated by hardhat-viem, do not edit it.
// prettier-ignore
// tslint:disable
// eslint-disable

import type { Address } from "viem";
import type { GetContractReturnType } from "@nomicfoundation/hardhat-viem/types";
import "@nomicfoundation/hardhat-viem/types";

export interface EthereumUtils$Type {
  "_format": "hh-sol-artifact-1",
  "contractName": "EthereumUtils",
  "sourceName": "@oasisprotocol/sapphire-contracts/contracts/EthereumUtils.sol",
  "abi": [
    {
      "inputs": [],
      "name": "DER_Split_Error",
      "type": "error"
    },
    {
      "inputs": [],
      "name": "expmod_Error",
      "type": "error"
    },
    {
      "inputs": [],
      "name": "k256Decompress_Invalid_Length_Error",
      "type": "error"
    },
    {
      "inputs": [],
      "name": "k256DeriveY_Invalid_Prefix_Error",
      "type": "error"
    },
    {
      "inputs": [],
      "name": "recoverV_Error",
      "type": "error"
    }
  ],
  "bytecode": "0x60566050600b82828239805160001a6073146043577f4e487b7100000000000000000000000000000000000000000000000000000000600052600060045260246000fd5b30600052607381538281f3fe73000000000000000000000000000000000000000030146080604052600080fdfea264697066735822122040024055dfef70eb214ae2de26805e24f5e2a793ca607c268af6fed63aecebb364736f6c634300081e0033",
  "deployedBytecode": "0x73000000000000000000000000000000000000000030146080604052600080fdfea264697066735822122040024055dfef70eb214ae2de26805e24f5e2a793ca607c268af6fed63aecebb364736f6c634300081e0033",
  "linkReferences": {},
  "deployedLinkReferences": {}
}

declare module "@nomicfoundation/hardhat-viem/types" {
  export function deployContract(
    contractName: "EthereumUtils",
    constructorArgs?: [],
    config?: DeployContractConfig
  ): Promise<GetContractReturnType<EthereumUtils$Type["abi"]>>;
  export function deployContract(
    contractName: "@oasisprotocol/sapphire-contracts/contracts/EthereumUtils.sol:EthereumUtils",
    constructorArgs?: [],
    config?: DeployContractConfig
  ): Promise<GetContractReturnType<EthereumUtils$Type["abi"]>>;

  export function sendDeploymentTransaction(
    contractName: "EthereumUtils",
    constructorArgs?: [],
    config?: SendDeploymentTransactionConfig
  ): Promise<{
    contract: GetContractReturnType<EthereumUtils$Type["abi"]>;
    deploymentTransaction: GetTransactionReturnType;
  }>;
  export function sendDeploymentTransaction(
    contractName: "@oasisprotocol/sapphire-contracts/contracts/EthereumUtils.sol:EthereumUtils",
    constructorArgs?: [],
    config?: SendDeploymentTransactionConfig
  ): Promise<{
    contract: GetContractReturnType<EthereumUtils$Type["abi"]>;
    deploymentTransaction: GetTransactionReturnType;
  }>;

  export function getContractAt(
    contractName: "EthereumUtils",
    address: Address,
    config?: GetContractAtConfig
  ): Promise<GetContractReturnType<EthereumUtils$Type["abi"]>>;
  export function getContractAt(
    contractName: "@oasisprotocol/sapphire-contracts/contracts/EthereumUtils.sol:EthereumUtils",
    address: Address,
    config?: GetContractAtConfig
  ): Promise<GetContractReturnType<EthereumUtils$Type["abi"]>>;
}
