// This file was autogenerated by hardhat-viem, do not edit it.
// prettier-ignore
// tslint:disable
// eslint-disable

import "hardhat/types/artifacts";
import type { GetContractReturnType } from "@nomicfoundation/hardhat-viem/types";

import { ConfidentialBalanceRegistry$Type } from "./ConfidentialBalanceRegistry";

declare module "hardhat/types/artifacts" {
  interface ArtifactsMap {
    ["ConfidentialBalanceRegistry"]: ConfidentialBalanceRegistry$Type;
    ["contracts/confidentialERC20/BalanceRegistry.sol:ConfidentialBalanceRegistry"]: ConfidentialBalanceRegistry$Type;
  }

  interface ContractTypesMap {
    ["ConfidentialBalanceRegistry"]: GetContractReturnType<ConfidentialBalanceRegistry$Type["abi"]>;
    ["contracts/confidentialERC20/BalanceRegistry.sol:ConfidentialBalanceRegistry"]: GetContractReturnType<ConfidentialBalanceRegistry$Type["abi"]>;
  }
}
