// This file was autogenerated by hardhat-viem, do not edit it.
// prettier-ignore
// tslint:disable
// eslint-disable

import type { Address } from "viem";
import type { GetContractReturnType } from "@nomicfoundation/hardhat-viem/types";
import "@nomicfoundation/hardhat-viem/types";

export interface Panic$Type {
  "_format": "hh-sol-artifact-1",
  "contractName": "Panic",
  "sourceName": "@openzeppelin/contracts/utils/Panic.sol",
  "abi": [],
  "bytecode": "0x60566050600b82828239805160001a6073146043577f4e487b7100000000000000000000000000000000000000000000000000000000600052600060045260246000fd5b30600052607381538281f3fe73000000000000000000000000000000000000000030146080604052600080fdfea2646970667358221220f57b1869b58b4cb71ec7a4d76fb81f71ae78cd3cd6d2875b53a0f5d369f861b364736f6c634300081e0033",
  "deployedBytecode": "0x73000000000000000000000000000000000000000030146080604052600080fdfea2646970667358221220f57b1869b58b4cb71ec7a4d76fb81f71ae78cd3cd6d2875b53a0f5d369f861b364736f6c634300081e0033",
  "linkReferences": {},
  "deployedLinkReferences": {}
}

declare module "@nomicfoundation/hardhat-viem/types" {
  export function deployContract(
    contractName: "Panic",
    constructorArgs?: [],
    config?: DeployContractConfig
  ): Promise<GetContractReturnType<Panic$Type["abi"]>>;
  export function deployContract(
    contractName: "@openzeppelin/contracts/utils/Panic.sol:Panic",
    constructorArgs?: [],
    config?: DeployContractConfig
  ): Promise<GetContractReturnType<Panic$Type["abi"]>>;

  export function sendDeploymentTransaction(
    contractName: "Panic",
    constructorArgs?: [],
    config?: SendDeploymentTransactionConfig
  ): Promise<{
    contract: GetContractReturnType<Panic$Type["abi"]>;
    deploymentTransaction: GetTransactionReturnType;
  }>;
  export function sendDeploymentTransaction(
    contractName: "@openzeppelin/contracts/utils/Panic.sol:Panic",
    constructorArgs?: [],
    config?: SendDeploymentTransactionConfig
  ): Promise<{
    contract: GetContractReturnType<Panic$Type["abi"]>;
    deploymentTransaction: GetTransactionReturnType;
  }>;

  export function getContractAt(
    contractName: "Panic",
    address: Address,
    config?: GetContractAtConfig
  ): Promise<GetContractReturnType<Panic$Type["abi"]>>;
  export function getContractAt(
    contractName: "@openzeppelin/contracts/utils/Panic.sol:Panic",
    address: Address,
    config?: GetContractAtConfig
  ): Promise<GetContractReturnType<Panic$Type["abi"]>>;
}
