version: '3'

services:
  roflswap-matcher:
    build:
      context: .
      dockerfile: Dockerfile
    image: ghcr.io/oasisprotocol/roflswap-matcher:latest
    platform: linux/amd64
    restart: always
    environment:
      - ROFLSWAP_ADDRESS=0x1bc94B51C5040E7A64FE5F42F51C328d7398969e
      - POLLING_INTERVAL=30
    volumes:
      - /run/rofl-appd.sock:/run/rofl-appd.sock
      - ./storage:/app/storage
    command: --contract 0x1bc94B51C5040E7A64FE5F42F51C328d7398969e --interval 30
