services:
  roflswap-order-matcher:
    build: .
    image: "roflswap-order-matcher"
    platform: linux/amd64
    volumes:
      - ./storage:/app/storage
    environment:
      - ROFLSWAP_ADDRESS=${ROFLSWAP_ADDRESS}
      - WEB3_PROVIDER=${WEB3_PROVIDER}
      - PRIVATE_KEY=${PRIVATE_KEY}
