services:
  roflswap-matcher:
    build: .
    image: "ghcr.io/your-username/roflswap-matcher:latest"
    platform: linux/amd64
    environment:
      - PRIVATE_KEY=${PRIVATE_KEY}
      - ROFLSWAP_ADDRESS=${ROFLSWAP_ADDRESS}
      - WEB3_PROVIDER=${WEB3_PROVIDER}
      - ROFL_APP_ID=${ROFL_APP_ID}
    volumes:
      - /run/rofl-appd.sock:/run/rofl-appd.sock
      - ./storage:/app/storage
