// This file was autogenerated by hardhat-viem, do not edit it.
// prettier-ignore
// tslint:disable
// eslint-disable

import type { Address } from "viem";
import type { GetContractReturnType } from "@nomicfoundation/hardhat-viem/types";
import "@nomicfoundation/hardhat-viem/types";

export interface A13e$Type {
  "_format": "hh-sol-artifact-1",
  "contractName": "A13e",
  "sourceName": "@oasisprotocol/sapphire-contracts/contracts/auth/A13e.sol",
  "abi": [
    {
      "inputs": [],
      "name": "A13e_RevokedAuthToken",
      "type": "error"
    },
    {
      "inputs": [
        {
          "internalType": "string",
          "name": "message",
          "type": "string"
        },
        {
          "components": [
            {
              "internalType": "bytes32",
              "name": "r",
              "type": "bytes32"
            },
            {
              "internalType": "bytes32",
              "name": "s",
              "type": "bytes32"
            },
            {
              "internalType": "uint256",
              "name": "v",
              "type": "uint256"
            }
          ],
          "internalType": "struct SignatureRSV",
          "name": "sig",
          "type": "tuple"
        }
      ],
      "name": "login",
      "outputs": [
        {
          "internalType": "bytes",
          "name": "",
          "type": "bytes"
        }
      ],
      "stateMutability": "view",
      "type": "function"
    }
  ],
  "bytecode": "0x",
  "deployedBytecode": "0x",
  "linkReferences": {},
  "deployedLinkReferences": {}
}

declare module "@nomicfoundation/hardhat-viem/types" {
  export function deployContract(
    contractName: "A13e",
    constructorArgs?: [],
    config?: DeployContractConfig
  ): Promise<GetContractReturnType<A13e$Type["abi"]>>;
  export function deployContract(
    contractName: "@oasisprotocol/sapphire-contracts/contracts/auth/A13e.sol:A13e",
    constructorArgs?: [],
    config?: DeployContractConfig
  ): Promise<GetContractReturnType<A13e$Type["abi"]>>;

  export function sendDeploymentTransaction(
    contractName: "A13e",
    constructorArgs?: [],
    config?: SendDeploymentTransactionConfig
  ): Promise<{
    contract: GetContractReturnType<A13e$Type["abi"]>;
    deploymentTransaction: GetTransactionReturnType;
  }>;
  export function sendDeploymentTransaction(
    contractName: "@oasisprotocol/sapphire-contracts/contracts/auth/A13e.sol:A13e",
    constructorArgs?: [],
    config?: SendDeploymentTransactionConfig
  ): Promise<{
    contract: GetContractReturnType<A13e$Type["abi"]>;
    deploymentTransaction: GetTransactionReturnType;
  }>;

  export function getContractAt(
    contractName: "A13e",
    address: Address,
    config?: GetContractAtConfig
  ): Promise<GetContractReturnType<A13e$Type["abi"]>>;
  export function getContractAt(
    contractName: "@oasisprotocol/sapphire-contracts/contracts/auth/A13e.sol:A13e",
    address: Address,
    config?: GetContractAtConfig
  ): Promise<GetContractReturnType<A13e$Type["abi"]>>;
}
