// This file was autogenerated by hardhat-viem, do not edit it.
// prettier-ignore
// tslint:disable
// eslint-disable

import "hardhat/types/artifacts";
import type { GetContractReturnType } from "@nomicfoundation/hardhat-viem/types";

import { A13e$Type } from "./A13e";

declare module "hardhat/types/artifacts" {
  interface ArtifactsMap {
    ["A13e"]: A13e$Type;
    ["@oasisprotocol/sapphire-contracts/contracts/auth/A13e.sol:A13e"]: A13e$Type;
  }

  interface ContractTypesMap {
    ["A13e"]: GetContractReturnType<A13e$Type["abi"]>;
    ["@oasisprotocol/sapphire-contracts/contracts/auth/A13e.sol:A13e"]: GetContractReturnType<A13e$Type["abi"]>;
  }
}
