// This file was autogenerated by hardhat-viem, do not edit it.
// prettier-ignore
// tslint:disable
// eslint-disable

import "hardhat/types/artifacts";
import type { GetContractReturnType } from "@nomicfoundation/hardhat-viem/types";

import { ROFLSwapOracle$Type } from "./ROFLSwapOracle";

declare module "hardhat/types/artifacts" {
  interface ArtifactsMap {
    ["ROFLSwapOracle"]: ROFLSwapOracle$Type;
    ["contracts/ROFLSwapOracle.sol:ROFLSwapOracle"]: ROFLSwapOracle$Type;
  }

  interface ContractTypesMap {
    ["ROFLSwapOracle"]: GetContractReturnType<ROFLSwapOracle$Type["abi"]>;
    ["contracts/ROFLSwapOracle.sol:ROFLSwapOracle"]: GetContractReturnType<ROFLSwapOracle$Type["abi"]>;
  }
}
