// This file was autogenerated by hardhat-viem, do not edit it.
// prettier-ignore
// tslint:disable
// eslint-disable

import "hardhat/types/artifacts";
import type { GetContractReturnType } from "@nomicfoundation/hardhat-viem/types";

import { ConsensusUtils$Type } from "./ConsensusUtils";

declare module "hardhat/types/artifacts" {
  interface ArtifactsMap {
    ["ConsensusUtils"]: ConsensusUtils$Type;
    ["@oasisprotocol/sapphire-contracts/contracts/ConsensusUtils.sol:ConsensusUtils"]: ConsensusUtils$Type;
  }

  interface ContractTypesMap {
    ["ConsensusUtils"]: GetContractReturnType<ConsensusUtils$Type["abi"]>;
    ["@oasisprotocol/sapphire-contracts/contracts/ConsensusUtils.sol:ConsensusUtils"]: GetContractReturnType<ConsensusUtils$Type["abi"]>;
  }
}
