// This file was autogenerated by hardhat-viem, do not edit it.
// prettier-ignore
// tslint:disable
// eslint-disable

import type { Address } from "viem";
import type { GetContractReturnType } from "@nomicfoundation/hardhat-viem/types";
import "@nomicfoundation/hardhat-viem/types";

export interface ConsensusUtils$Type {
  "_format": "hh-sol-artifact-1",
  "contractName": "ConsensusUtils",
  "sourceName": "@oasisprotocol/sapphire-contracts/contracts/ConsensusUtils.sol",
  "abi": [],
  "bytecode": "0x60566050600b82828239805160001a6073146043577f4e487b7100000000000000000000000000000000000000000000000000000000600052600060045260246000fd5b30600052607381538281f3fe73000000000000000000000000000000000000000030146080604052600080fdfea2646970667358221220368ff35489f911eb33a21b9e362dc352a1a223a286f4509dd752671be1713ed664736f6c634300081c0033",
  "deployedBytecode": "0x73000000000000000000000000000000000000000030146080604052600080fdfea2646970667358221220368ff35489f911eb33a21b9e362dc352a1a223a286f4509dd752671be1713ed664736f6c634300081c0033",
  "linkReferences": {},
  "deployedLinkReferences": {}
}

declare module "@nomicfoundation/hardhat-viem/types" {
  export function deployContract(
    contractName: "ConsensusUtils",
    constructorArgs?: [],
    config?: DeployContractConfig
  ): Promise<GetContractReturnType<ConsensusUtils$Type["abi"]>>;
  export function deployContract(
    contractName: "@oasisprotocol/sapphire-contracts/contracts/ConsensusUtils.sol:ConsensusUtils",
    constructorArgs?: [],
    config?: DeployContractConfig
  ): Promise<GetContractReturnType<ConsensusUtils$Type["abi"]>>;

  export function sendDeploymentTransaction(
    contractName: "ConsensusUtils",
    constructorArgs?: [],
    config?: SendDeploymentTransactionConfig
  ): Promise<{
    contract: GetContractReturnType<ConsensusUtils$Type["abi"]>;
    deploymentTransaction: GetTransactionReturnType;
  }>;
  export function sendDeploymentTransaction(
    contractName: "@oasisprotocol/sapphire-contracts/contracts/ConsensusUtils.sol:ConsensusUtils",
    constructorArgs?: [],
    config?: SendDeploymentTransactionConfig
  ): Promise<{
    contract: GetContractReturnType<ConsensusUtils$Type["abi"]>;
    deploymentTransaction: GetTransactionReturnType;
  }>;

  export function getContractAt(
    contractName: "ConsensusUtils",
    address: Address,
    config?: GetContractAtConfig
  ): Promise<GetContractReturnType<ConsensusUtils$Type["abi"]>>;
  export function getContractAt(
    contractName: "@oasisprotocol/sapphire-contracts/contracts/ConsensusUtils.sol:ConsensusUtils",
    address: Address,
    config?: GetContractAtConfig
  ): Promise<GetContractReturnType<ConsensusUtils$Type["abi"]>>;
}
