// This file was autogenerated by hardhat-viem, do not edit it.
// prettier-ignore
// tslint:disable
// eslint-disable

import "hardhat/types/artifacts";
import type { GetContractReturnType } from "@nomicfoundation/hardhat-viem/types";

import { SiweAuth$Type } from "./SiweAuth";

declare module "hardhat/types/artifacts" {
  interface ArtifactsMap {
    ["SiweAuth"]: SiweAuth$Type;
    ["@oasisprotocol/sapphire-contracts/contracts/auth/SiweAuth.sol:SiweAuth"]: SiweAuth$Type;
  }

  interface ContractTypesMap {
    ["SiweAuth"]: GetContractReturnType<SiweAuth$Type["abi"]>;
    ["@oasisprotocol/sapphire-contracts/contracts/auth/SiweAuth.sol:SiweAuth"]: GetContractReturnType<SiweAuth$Type["abi"]>;
  }
}
