// This file was autogenerated by hardhat-viem, do not edit it.
// prettier-ignore
// tslint:disable
// eslint-disable

import "hardhat/types/artifacts";
import type { GetContractReturnType } from "@nomicfoundation/hardhat-viem/types";

import { AccessControl$Type } from "./AccessControl";

declare module "hardhat/types/artifacts" {
  interface ArtifactsMap {
    ["AccessControl"]: AccessControl$Type;
    ["@openzeppelin/contracts/access/AccessControl.sol:AccessControl"]: AccessControl$Type;
  }

  interface ContractTypesMap {
    ["AccessControl"]: GetContractReturnType<AccessControl$Type["abi"]>;
    ["@openzeppelin/contracts/access/AccessControl.sol:AccessControl"]: GetContractReturnType<AccessControl$Type["abi"]>;
  }
}
