// This file was autogenerated by hardhat-viem, do not edit it.
// prettier-ignore
// tslint:disable
// eslint-disable

import "hardhat/types/artifacts";
import type { GetContractReturnType } from "@nomicfoundation/hardhat-viem/types";

import { MockToken$Type } from "./MockToken";

declare module "hardhat/types/artifacts" {
  interface ArtifactsMap {
    ["MockToken"]: MockToken$Type;
    ["contracts/MockToken.sol:MockToken"]: MockToken$Type;
  }

  interface ContractTypesMap {
    ["MockToken"]: GetContractReturnType<MockToken$Type["abi"]>;
    ["contracts/MockToken.sol:MockToken"]: GetContractReturnType<MockToken$Type["abi"]>;
  }
}
