// This file was autogenerated by hardhat-viem, do not edit it.
// prettier-ignore
// tslint:disable
// eslint-disable

import "hardhat/types/artifacts";
import type { GetContractReturnType } from "@nomicfoundation/hardhat-viem/types";

import { SafeERC20$Type } from "./SafeERC20";

declare module "hardhat/types/artifacts" {
  interface ArtifactsMap {
    ["SafeERC20"]: SafeERC20$Type;
    ["@openzeppelin/contracts/token/ERC20/utils/SafeERC20.sol:SafeERC20"]: SafeERC20$Type;
  }

  interface ContractTypesMap {
    ["SafeERC20"]: GetContractReturnType<SafeERC20$Type["abi"]>;
    ["@openzeppelin/contracts/token/ERC20/utils/SafeERC20.sol:SafeERC20"]: GetContractReturnType<SafeERC20$Type["abi"]>;
  }
}
