// This file was autogenerated by hardhat-viem, do not edit it.
// prettier-ignore
// tslint:disable
// eslint-disable

import "hardhat/types/artifacts";
import type { GetContractReturnType } from "@nomicfoundation/hardhat-viem/types";

import { Bitmask$Type } from "./Bitmask";

declare module "hardhat/types/artifacts" {
  interface ArtifactsMap {
    ["Bitmask"]: Bitmask$Type;
    ["contracts/libraries/Bitmask.sol:Bitmask"]: Bitmask$Type;
  }

  interface ContractTypesMap {
    ["Bitmask"]: GetContractReturnType<Bitmask$Type["abi"]>;
    ["contracts/libraries/Bitmask.sol:Bitmask"]: GetContractReturnType<Bitmask$Type["abi"]>;
  }
}
