// This file was autogenerated by hardhat-viem, do not edit it.
// prettier-ignore
// tslint:disable
// eslint-disable

import type { Address } from "viem";
import type { GetContractReturnType } from "@nomicfoundation/hardhat-viem/types";
import "@nomicfoundation/hardhat-viem/types";

export interface Bitmask$Type {
  "_format": "hh-sol-artifact-1",
  "contractName": "Bitmask",
  "sourceName": "contracts/libraries/Bitmask.sol",
  "abi": [],
  "bytecode": "0x60566050600b82828239805160001a6073146043577f4e487b7100000000000000000000000000000000000000000000000000000000600052600060045260246000fd5b30600052607381538281f3fe73000000000000000000000000000000000000000030146080604052600080fdfea26469706673582212208ffe10d1ab9b8cd8ae649475f89dd6a970c9e99e50680cd0c2572e07ce82785464736f6c634300081e0033",
  "deployedBytecode": "0x73000000000000000000000000000000000000000030146080604052600080fdfea26469706673582212208ffe10d1ab9b8cd8ae649475f89dd6a970c9e99e50680cd0c2572e07ce82785464736f6c634300081e0033",
  "linkReferences": {},
  "deployedLinkReferences": {}
}

declare module "@nomicfoundation/hardhat-viem/types" {
  export function deployContract(
    contractName: "Bitmask",
    constructorArgs?: [],
    config?: DeployContractConfig
  ): Promise<GetContractReturnType<Bitmask$Type["abi"]>>;
  export function deployContract(
    contractName: "contracts/libraries/Bitmask.sol:Bitmask",
    constructorArgs?: [],
    config?: DeployContractConfig
  ): Promise<GetContractReturnType<Bitmask$Type["abi"]>>;

  export function sendDeploymentTransaction(
    contractName: "Bitmask",
    constructorArgs?: [],
    config?: SendDeploymentTransactionConfig
  ): Promise<{
    contract: GetContractReturnType<Bitmask$Type["abi"]>;
    deploymentTransaction: GetTransactionReturnType;
  }>;
  export function sendDeploymentTransaction(
    contractName: "contracts/libraries/Bitmask.sol:Bitmask",
    constructorArgs?: [],
    config?: SendDeploymentTransactionConfig
  ): Promise<{
    contract: GetContractReturnType<Bitmask$Type["abi"]>;
    deploymentTransaction: GetTransactionReturnType;
  }>;

  export function getContractAt(
    contractName: "Bitmask",
    address: Address,
    config?: GetContractAtConfig
  ): Promise<GetContractReturnType<Bitmask$Type["abi"]>>;
  export function getContractAt(
    contractName: "contracts/libraries/Bitmask.sol:Bitmask",
    address: Address,
    config?: GetContractAtConfig
  ): Promise<GetContractReturnType<Bitmask$Type["abi"]>>;
}
