// This file was autogenerated by hardhat-viem, do not edit it.
// prettier-ignore
// tslint:disable
// eslint-disable

import "hardhat/types/artifacts";
import type { GetContractReturnType } from "@nomicfoundation/hardhat-viem/types";

import { WaterToken$Type } from "./WaterToken";

declare module "hardhat/types/artifacts" {
  interface ArtifactsMap {
    ["WaterToken"]: WaterToken$Type;
    ["contracts/WaterToken.sol:WaterToken"]: WaterToken$Type;
  }

  interface ContractTypesMap {
    ["WaterToken"]: GetContractReturnType<WaterToken$Type["abi"]>;
    ["contracts/WaterToken.sol:WaterToken"]: GetContractReturnType<WaterToken$Type["abi"]>;
  }
}
