// This file was autogenerated by hardhat-viem, do not edit it.
// prettier-ignore
// tslint:disable
// eslint-disable

import "hardhat/types/artifacts";
import type { GetContractReturnType } from "@nomicfoundation/hardhat-viem/types";

import { LuminexPrivacyPolicy$Type } from "./LuminexPrivacyPolicy";

declare module "hardhat/types/artifacts" {
  interface ArtifactsMap {
    ["LuminexPrivacyPolicy"]: LuminexPrivacyPolicy$Type;
    ["contracts/confidentialERC20/LuminexPrivacyPolicy.sol:LuminexPrivacyPolicy"]: LuminexPrivacyPolicy$Type;
  }

  interface ContractTypesMap {
    ["LuminexPrivacyPolicy"]: GetContractReturnType<LuminexPrivacyPolicy$Type["abi"]>;
    ["contracts/confidentialERC20/LuminexPrivacyPolicy.sol:LuminexPrivacyPolicy"]: GetContractReturnType<LuminexPrivacyPolicy$Type["abi"]>;
  }
}
