// This file was autogenerated by hardhat-viem, do not edit it.
// prettier-ignore
// tslint:disable
// eslint-disable

import "hardhat/types/artifacts";
import type { GetContractReturnType } from "@nomicfoundation/hardhat-viem/types";

import { ROFLSwapV2$Type } from "./ROFLSwapV2";

declare module "hardhat/types/artifacts" {
  interface ArtifactsMap {
    ["ROFLSwapV2"]: ROFLSwapV2$Type;
    ["contracts/ROFLSwapV2.sol:ROFLSwapV2"]: ROFLSwapV2$Type;
  }

  interface ContractTypesMap {
    ["ROFLSwapV2"]: GetContractReturnType<ROFLSwapV2$Type["abi"]>;
    ["contracts/ROFLSwapV2.sol:ROFLSwapV2"]: GetContractReturnType<ROFLSwapV2$Type["abi"]>;
  }
}
