// This file was autogenerated by hardhat-viem, do not edit it.
// prettier-ignore
// tslint:disable
// eslint-disable

import "hardhat/types/artifacts";
import type { GetContractReturnType } from "@nomicfoundation/hardhat-viem/types";

import { ERC20Mintable$Type } from "./ERC20Mintable";

declare module "hardhat/types/artifacts" {
  interface ArtifactsMap {
    ["ERC20Mintable"]: ERC20Mintable$Type;
    ["contracts/ERC20Mintable.sol:ERC20Mintable"]: ERC20Mintable$Type;
  }

  interface ContractTypesMap {
    ["ERC20Mintable"]: GetContractReturnType<ERC20Mintable$Type["abi"]>;
    ["contracts/ERC20Mintable.sol:ERC20Mintable"]: GetContractReturnType<ERC20Mintable$Type["abi"]>;
  }
}
