// This file was autogenerated by hardhat-viem, do not edit it.
// prettier-ignore
// tslint:disable
// eslint-disable

import "hardhat/types/artifacts";
import type { GetContractReturnType } from "@nomicfoundation/hardhat-viem/types";

import { ROFLSwapV3$Type } from "./ROFLSwapV3";

declare module "hardhat/types/artifacts" {
  interface ArtifactsMap {
    ["ROFLSwapV3"]: ROFLSwapV3$Type;
    ["contracts/ROFLSwapV3.sol:ROFLSwapV3"]: ROFLSwapV3$Type;
  }

  interface ContractTypesMap {
    ["ROFLSwapV3"]: GetContractReturnType<ROFLSwapV3$Type["abi"]>;
    ["contracts/ROFLSwapV3.sol:ROFLSwapV3"]: GetContractReturnType<ROFLSwapV3$Type["abi"]>;
  }
}
