// This file was autogenerated by hardhat-viem, do not edit it.
// prettier-ignore
// tslint:disable
// eslint-disable

import "hardhat/types/artifacts";
import type { GetContractReturnType } from "@nomicfoundation/hardhat-viem/types";

import { ROFLSwap$Type } from "./ROFLSwap";

declare module "hardhat/types/artifacts" {
  interface ArtifactsMap {
    ["ROFLSwap"]: ROFLSwap$Type;
    ["contracts/ROFLSwap.sol:ROFLSwap"]: ROFLSwap$Type;
  }

  interface ContractTypesMap {
    ["ROFLSwap"]: GetContractReturnType<ROFLSwap$Type["abi"]>;
    ["contracts/ROFLSwap.sol:ROFLSwap"]: GetContractReturnType<ROFLSwap$Type["abi"]>;
  }
}
