// This file was autogenerated by hardhat-viem, do not edit it.
// prettier-ignore
// tslint:disable
// eslint-disable

import "hardhat/types/artifacts";
import type { GetContractReturnType } from "@nomicfoundation/hardhat-viem/types";

import { ROFLSwapTester$Type } from "./ROFLSwapTester";

declare module "hardhat/types/artifacts" {
  interface ArtifactsMap {
    ["ROFLSwapTester"]: ROFLSwapTester$Type;
    ["contracts/ROFLSwapTester.sol:ROFLSwapTester"]: ROFLSwapTester$Type;
  }

  interface ContractTypesMap {
    ["ROFLSwapTester"]: GetContractReturnType<ROFLSwapTester$Type["abi"]>;
    ["contracts/ROFLSwapTester.sol:ROFLSwapTester"]: GetContractReturnType<ROFLSwapTester$Type["abi"]>;
  }
}
