// This file was autogenerated by hardhat-viem, do not edit it.
// prettier-ignore
// tslint:disable
// eslint-disable

import "hardhat/types/artifacts";
import type { GetContractReturnType } from "@nomicfoundation/hardhat-viem/types";

import { CustomOwnable$Type } from "./CustomOwnable";

declare module "hardhat/types/artifacts" {
  interface ArtifactsMap {
    ["CustomOwnable"]: CustomOwnable$Type;
    ["contracts/confidentialERC20/custom/CustomOwnable.sol:CustomOwnable"]: CustomOwnable$Type;
  }

  interface ContractTypesMap {
    ["CustomOwnable"]: GetContractReturnType<CustomOwnable$Type["abi"]>;
    ["contracts/confidentialERC20/custom/CustomOwnable.sol:CustomOwnable"]: GetContractReturnType<CustomOwnable$Type["abi"]>;
  }
}
