// This file was autogenerated by hardhat-viem, do not edit it.
// prettier-ignore
// tslint:disable
// eslint-disable

import "hardhat/types/artifacts";
import type { GetContractReturnType } from "@nomicfoundation/hardhat-viem/types";

import { PrivateERC20$Type } from "./PrivateERC20";

declare module "hardhat/types/artifacts" {
  interface ArtifactsMap {
    ["PrivateERC20"]: PrivateERC20$Type;
    ["contracts/PrivateERC20.sol:PrivateERC20"]: PrivateERC20$Type;
  }

  interface ContractTypesMap {
    ["PrivateERC20"]: GetContractReturnType<PrivateERC20$Type["abi"]>;
    ["contracts/PrivateERC20.sol:PrivateERC20"]: GetContractReturnType<PrivateERC20$Type["abi"]>;
  }
}
