// This file was autogenerated by hardhat-viem, do not edit it.
// prettier-ignore
// tslint:disable
// eslint-disable

import "hardhat/types/artifacts";
import type { GetContractReturnType } from "@nomicfoundation/hardhat-viem/types";

import { ROFLSwapV4$Type } from "./ROFLSwapV4";

declare module "hardhat/types/artifacts" {
  interface ArtifactsMap {
    ["ROFLSwapV4"]: ROFLSwapV4$Type;
    ["contracts/ROFLSwapV4.sol:ROFLSwapV4"]: ROFLSwapV4$Type;
  }

  interface ContractTypesMap {
    ["ROFLSwapV4"]: GetContractReturnType<ROFLSwapV4$Type["abi"]>;
    ["contracts/ROFLSwapV4.sol:ROFLSwapV4"]: GetContractReturnType<ROFLSwapV4$Type["abi"]>;
  }
}
