// This file was autogenerated by hardhat-viem, do not edit it.
// prettier-ignore
// tslint:disable
// eslint-disable

import "hardhat/types/artifacts";
import type { GetContractReturnType } from "@nomicfoundation/hardhat-viem/types";

import { ERC20$Type } from "./ERC20";

declare module "hardhat/types/artifacts" {
  interface ArtifactsMap {
    ["ERC20"]: ERC20$Type;
    ["@openzeppelin/contracts/token/ERC20/ERC20.sol:ERC20"]: ERC20$Type;
  }

  interface ContractTypesMap {
    ["ERC20"]: GetContractReturnType<ERC20$Type["abi"]>;
    ["@openzeppelin/contracts/token/ERC20/ERC20.sol:ERC20"]: GetContractReturnType<ERC20$Type["abi"]>;
  }
}
