// This file was autogenerated by hardhat-viem, do not edit it.
// prettier-ignore
// tslint:disable
// eslint-disable

import "hardhat/types/artifacts";
import type { GetContractReturnType } from "@nomicfoundation/hardhat-viem/types";

import { Sapphire$Type } from "./Sapphire";

declare module "hardhat/types/artifacts" {
  interface ArtifactsMap {
    ["Sapphire"]: Sapphire$Type;
    ["@oasisprotocol/sapphire-contracts/contracts/Sapphire.sol:Sapphire"]: Sapphire$Type;
  }

  interface ContractTypesMap {
    ["Sapphire"]: GetContractReturnType<Sapphire$Type["abi"]>;
    ["@oasisprotocol/sapphire-contracts/contracts/Sapphire.sol:Sapphire"]: GetContractReturnType<Sapphire$Type["abi"]>;
  }
}
