// This file was autogenerated by hardhat-viem, do not edit it.
// prettier-ignore
// tslint:disable
// eslint-disable

import type { Address } from "viem";
import type { GetContractReturnType } from "@nomicfoundation/hardhat-viem/types";
import "@nomicfoundation/hardhat-viem/types";

export interface Sapphire$Type {
  "_format": "hh-sol-artifact-1",
  "contractName": "Sapphire",
  "sourceName": "@oasisprotocol/sapphire-contracts/contracts/Sapphire.sol",
  "abi": [],
  "bytecode": "0x60566050600b82828239805160001a6073146043577f4e487b7100000000000000000000000000000000000000000000000000000000600052600060045260246000fd5b30600052607381538281f3fe73000000000000000000000000000000000000000030146080604052600080fdfea26469706673582212209bc8665da10f110f58a9f6fb09dbb8899fa26da2b458983f9584cb2c0420086e64736f6c634300081e0033",
  "deployedBytecode": "0x73000000000000000000000000000000000000000030146080604052600080fdfea26469706673582212209bc8665da10f110f58a9f6fb09dbb8899fa26da2b458983f9584cb2c0420086e64736f6c634300081e0033",
  "linkReferences": {},
  "deployedLinkReferences": {}
}

declare module "@nomicfoundation/hardhat-viem/types" {
  export function deployContract(
    contractName: "Sapphire",
    constructorArgs?: [],
    config?: DeployContractConfig
  ): Promise<GetContractReturnType<Sapphire$Type["abi"]>>;
  export function deployContract(
    contractName: "@oasisprotocol/sapphire-contracts/contracts/Sapphire.sol:Sapphire",
    constructorArgs?: [],
    config?: DeployContractConfig
  ): Promise<GetContractReturnType<Sapphire$Type["abi"]>>;

  export function sendDeploymentTransaction(
    contractName: "Sapphire",
    constructorArgs?: [],
    config?: SendDeploymentTransactionConfig
  ): Promise<{
    contract: GetContractReturnType<Sapphire$Type["abi"]>;
    deploymentTransaction: GetTransactionReturnType;
  }>;
  export function sendDeploymentTransaction(
    contractName: "@oasisprotocol/sapphire-contracts/contracts/Sapphire.sol:Sapphire",
    constructorArgs?: [],
    config?: SendDeploymentTransactionConfig
  ): Promise<{
    contract: GetContractReturnType<Sapphire$Type["abi"]>;
    deploymentTransaction: GetTransactionReturnType;
  }>;

  export function getContractAt(
    contractName: "Sapphire",
    address: Address,
    config?: GetContractAtConfig
  ): Promise<GetContractReturnType<Sapphire$Type["abi"]>>;
  export function getContractAt(
    contractName: "@oasisprotocol/sapphire-contracts/contracts/Sapphire.sol:Sapphire",
    address: Address,
    config?: GetContractAtConfig
  ): Promise<GetContractReturnType<Sapphire$Type["abi"]>>;
}
